const tipArray = [
    "Making a budget is the easy part. Next, you need to put it into action. But remember: a budget is not a permanently fixed thing. On the contrary, it is meant to be dynamic. So update it when things change.",
    "Challenge yourself to see how much you can save and pinch the pennies tighter every month. Set yourself a savings goal and be determined to set aside that money each month. Even if it’s just $10 a month, by the end of the year, that will be $120.",
    "Write down every purchase you make or use a budget app like Pearlopoly. Simply tracking what you spend can help you notice patterns, make you more aware of where your money is going, and help you identifyif you need to make a change.",
    "By planning out your meals for the coming week, you know the exact ingredients you need to buy. Make a shopping list and shop strategically. Only buy what you need. This also helps reduce wasted food at the end of the week.",
    "Borrow books from the library (just make sure to take your books back on time so you don’t incur a late fee)",
    "Apply for scholarships, awards, and bursaries. Many scholarships don’t receive very many applications, so it’s worth putting in the effort and going for it.",
    "The dollar store should always be your first destination when you’re shopping for household goods, school supplies, and more. Thrift stores are great for used clothing.",
    "While many stores offer discounts to students, these deals are not always advertised. Don’t be afraid to inquire with a store employee. Have your student card ready. Ask and (sometimes) you shall receive.",
    "Limiting the number of times you eat out each month can save you huge amounts of money. Cook big meals and put the rest in Tupperware containers. Bring the leftovers with you to school and heat them up to save money on meals.",
    "Instead, buy coffee beans in bulk and make it yourself. Purchase a travel mug and bring it with you to campus to keep your coffee warm.",
    "Not buying take-out coffee can save you a small fortune.",
    "Get your hands on as many coupons as you can, and use them to reduce your expenditure.",
    "Create a spreadsheet and compare your income and expenses for the next year. Are you in the green (income greater than expenses)? Great! Make sure you’re saving money every month.",
    "But, of course, you can’t avoid buying certain things. So when you do need to spend, take steps to reduce the cash you’re dishing out.",
    "While it seems like a simple distinction, you would be surprised at our ability to rationalize certain spending decisions. Saving money by buying only what you need gives you more flexibility in your budget in the long run.",
    "Don’t make purchasing decisions on the spot without thinking about the consequences.",
    "It’s better to buy fewer things that are higher quality because these tend to last much longer than cheaper alternatives. Why contribute to fast fashion by purchasing 20 pairs of cheap sunnies, when you can purchase a few classic shades from our extensive designer range that you'll have for many years?",
    "Buy used textbooks from former students instead of new ones.",
    "Go hiking, cycling, sightseeing, or take a walk in the park. Activities related to nature are best.",
    "At the grocery store, buy the house brand products. The dollar or two you save adds up over time.",
    "Making a monthly budget is the first step towards staying on top of your finances. Budgeting gives you a big-picture view of your money, so you can make informed spending and saving decisions.",
    "Always ask if there is a student discount before buying anything.",
    "Saving is more than just putting money away for a rainy day, it’s about developing positive habits and a sense of self control over your spending. Look online for frugal living or minimalist lifestyle groups and blogs to inspire you.",
    "When you’re looking to buy something, consider if and where you can get it for cheaper and don’t shy away from buying second-hand. Pre-loved items are a great way to save money, be more eco-friendly and help a good cause all at the same time. In fact, you’re helping the Earth by keeping unwanted item out of landfills.",
    "There are plenty of activities that you can do for free. Look at tourist-centred websites to find museums, exhibitions, events and festivals. ",
    "If you buy a coffee per day at $3 per cup, that will end up costing you $600 over the school year. I repeat, $600.",
    "You can also item swap with others and upcycle old items.",
    "Cooking from scratch is much cheaper than buying ready meals or takeaways. Meal planning is a good way to ensure you’re eating a healthy diet. This can also be a great way to limit your food waste as you tend to only buy what you'll cook.",
    "If you’re in the red (expenses greater than income), you’ll want to think about ways to reduce your spending or increase what you’re making each month.",
    "If you do want to spend money on a ‘want,’ check your budget first and see if you can afford it.",
    "Buying in bulk helps you get the most value out of each purchase.",
    "Buy value brands.",
    "Shop during the sales.",
    "This is self-explanatory. Whether it’s food, toiletries, or household products, choose the cheaper generic option as opposed to the top-of-the-line name brands.",
  ]

  export default tipArray;